name: Notify Telegram

on:
  schedule:
    - cron: "0 */2 * * *" # every 2 hours
  workflow_dispatch:

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Restore cache
        uses: actions/cache@v3
        with:
          path: group_ids.json
          key: group-ids-cache

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Send scheduled messages
        run: node index.js
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          JSONBIN_BIN_ID: ${{ secrets.JSONBIN_BIN_ID }}
          JSONBIN_API_KEY: ${{ secrets.JSONBIN_API_KEY }}

      - name: Save cache
        uses: actions/cache@v3
        with:
          path: group_ids.json
          key: group-ids-cache
